version: "3.9"

services:
  web:
    image: python:3.11-slim
    container_name: mydjango
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env   
    depends_on:
      - db
    command: >
      /bin/bash -c "
      pip install django psycopg2-binary python-decouple &&
      python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
